"use client";

import React from 'react';

const sections = [
    {
        title: "Indications for 3D-Printed Cranial Reconstruction",
        items: [
            "Post-traumatic cranial defects: Post Traumatic Brain Injury or decompressive craniectomy.",
            "Oncologic reconstruction: Post Tumor resection such as meningiomas or osteosarcomas.",
            "Congenital skull defects: Applicable in craniosynostosis and other developmental problems.",
            "Post infective cranial defects: Following osteomyelitis or bone loss through infection.",
            "Cosmetic and functional rehabilitation: To re-establish natural cranial anatomy to protect the intracranial structures."
        ]
    },
    {
        title: "The Role of 3D Printing in Cranioplasty",
        items: [
            "High resolution CT scans are used to generate smooth 3D printed models of the patient's cranial defect.",
            "A 3D model of the cranium could be generated by computer aided design (CAD) software, and patient specific cranial implant through virtual reconstruction and additive manufacturing.",
            "These patient customized cranial implants are manufactured to correct the defect size, shape and curvature resulting in optimized anatomical match, better protection of neural elements and aesthetic outcomes."
        ]
    },
    {
        title: "Benefits of 3D Printed Patient Specific Implants",
        items: [
            "Precise Fit: Custom made implants eliminate the need for intraoperative adjustments.",
            "Shorter Operative Time: Pre contoured implants streamline the surgical procedure.",
            "Enhanced Aesthetics: Achieving better symmetry and anatomy of the cranium.",
            "Biocompatible: The use of integrated, tissue-friendly materials like titanium and PEEK.",
            "Predictability: Preoperative preparation and virtual reality computer simulation aid in precision of surgical outcomes."
        ]
    }
];

const CranialIndications = () => {
    return (
        <section className="w-full pb-16 pt-8 bg-white">
            <div className="container mx-auto px-4 max-w-[1200px]">

                <div className="flex flex-col gap-6">
                    {sections.map((sec, sectionIndex) => (
                        <div
                            key={sectionIndex}
                            className="w-full bg-[#f4faff] border border-[#a4cbf3] rounded-xl overflow-hidden shadow-sm"
                        >
                            {/* Header Banner */}
                            <div className="bg-[#eaf4fd] px-6 py-4 border-b border-[#a4cbf3]">
                                <h3 className="text-[26px] font-bold text-[#1a5b9e] m-0">
                                    {sec.title}
                                </h3>
                            </div>

                            {/* List Content */}
                            <div className="px-8 py-6">
                                <ul className="space-y-4">
                                    {sec.items.map((item, itemIndex) => (
                                        <li key={itemIndex} className="flex text-gray-800 text-[16px] font-semibold">
                                            <span className="text-[#1a5b9e] mr-3 font-bold">•</span>
                                            <span dangerouslySetInnerHTML={{ __html: item.replace(/([^:]+):/, '<strong>$1:</strong>') }} />
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    ))}
                </div>

            </div>
        </section>
    );
};

export default CranialIndications;
