import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavTopBar from "../components/layout/NavTopBar";
import Navbar from "../components/layout/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: "normal",
  display: "swap",
  preload: true,

});


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <NavTopBar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
