import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavTopBar from "../components/layout/NavTopBar";
import Navbar from "../components/layout/Navbar";

import Footer from "../components/layout/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: "normal",
  display: "swap",
  preload: true,

});


export const metadata: Metadata = {
  title: "Medical 3D Printing Company & Custom Medical Device",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: '/opengraph-image.png',
        width: 1200,
        height: 630,
        alt: 'Medical 3D Printing Company & Custom Medical Device',
      },
    ],
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <NavTopBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
