import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavTopBar from "../components/layout/NavTopBar";
import Navbar from "../components/layout/Navbar";

import Footer from "../components/layout/Footer";
import FloatingButtons from "../components/common/FloatingButtons";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: "normal",
  display: "swap",
  preload: true,

});


export const metadata: Metadata = {
  title: "Medical 3D Printing Company & Custom Medical Device",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: '/opengraph-image.png',
        width: 1200,
        height: 630,
        alt: 'Medical 3D Printing Company & Custom Medical Device',
      },
    ],
  },

};

import GetQuoteForm from "../components/sections/get-quote/GetQuoteForm";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <NavTopBar />
        <Navbar />
        {children}

        {/* Global Quote Form Section */}
        <section className="w-full bg-[#f4f7f8] py-16 px-4">
          <div className="max-w-[800px] mx-auto bg-white p-8 rounded-2xl shadow-sm border border-gray-100">
            <div className="text-center mb-8">
              <h2 className="text-3xl font-bold text-[#1e73be] mb-3">Get a Quote</h2>
              <p className="text-gray-600">Fill out the form below and our team will get back to you shortly.</p>
            </div>
            <GetQuoteForm />
          </div>
        </section>

        <Footer />
        <FloatingButtons />
      </body>
    </html>
  );
}
