"use client";
import React, { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";

const faqs = [
    {
        question: "What is the Einscan H2 3D Scanner?",
        answer: "The Einscan H2 is a cutting-edge human body and color 3D scanner designed to capture detailed and accurate 3D scans of the entire human body or any part of the human body for medical and other engineering applications."
    },
    {
        question: "How does the Einscan H2 work for human body scanning?",
        answer: "The Einscan H2 utilizes white light and infrared light source technology to capture high-resolution 3D scans of the human body. It projects a pattern of light onto the human body and uses the deformation of the pattern to create a detailed 3D model."
    },
    {
        question: "Why is Einscan H2 the best 3D scanner for human body 3d scanning applications?",
        answer: "Einscan H2 is equipped with an Advanced Algorithm for Body Scanning applications to 3d scan the human body quickly with auto compensation of slight movements to eliminate misalignment risks. Also, veins can scan the dark and grey hairs very well."
    },
    {
        question: "Can a person move while scanning using an Einscan 3D scanner?",
        answer: "It’s recommended not to move while the person is being 3d scanned; however, slight movement can be adjusted while scanning, as the scanner has an algorithm to stitch the data and adjust the movement error."
    },
    {
        question: "Can the light from the 3d scanner cause any harm to the human body and the skin?",
        answer: "The light source of Einscan H 2 is skin and human-friendly, ideal for human body 3D scanning applications."
    },
    {
        question: "Besides medical applications, what are the other Human body 3D scanning applications for the Einscan H2 3D scanner?",
        answer: "Yes, the Einscan H2 is designed to capture full-body scans, providing detailed 3D models for various applications such as fitness tracking, apparel design, virtual try-on, custom tailoring, custom wig planning and making and many other applications related to the human body nowadays, being developed."
    },
    {
        question: "What is the scanning accuracy of the Einscan H2 for human body scanning?",
        answer: "The Einscan H2 offers an accurate, precise measurement of 0.1 mm for human body scanning 3D scan applications."
    },
    {
        question: "What file formats are supported for the 3D scans generated by the Einscan H2?",
        answer: "The Einscan H2 supports standard 3D file formats with colour options such as STL and OBJ, making it compatible with a wide range of 3D bio CAD and other 3D modelling and direct 3D printing."
    },
    {
        question: "What are the medical applications of Einscan H2?",
        answer: "The Einscan H2 3D scanner can be used in various medical applications, including Orthopedics, Facial prosthetics, Plastic Surgery, Physical Rehabilitation, Research and Development, Orthotics and Prosthetics, Burn and Wound Care."
    },
    {
        question: "Is training necessary for utilizing the Einscan H2 in human body scanning?",
        answer: "We at Graft3D provide on-site post-sale training for our customers who procure Einscan H2 from us. The Einscan H2 is a user-friendly 3D scanner for human body scanning that you can self-learn with the user manual and leverage our online training and videos."
    },
    {
        question: "To what region of the human body does the Einscan H2 3D scanner capture in one scan?",
        answer: "The Einscan H2 has a flexible scanning range, allowing for both close-up and broader scans; in one scan, einscan H2 can scan up to half the side of the face."
    },
    {
        question: "How long does scanning the human body using an Einscan H2 3D scanner take?",
        answer: "Users can complete the 3D scanning of the human body using Einscan H2 within 15 to 20 minutes at most."
    },
    {
        question: "Can Einscan H2 scan the internal human body?",
        answer: "No, It’s not like CT, CBCT, or MRI. The Einscan H2 3D scanner doesn’t scan the internal body parts; it scans only the external skin and hair of the human body."
    },
    {
        question: "Are there any post-processing steps required for Einscan H2 scans?",
        answer: "The Einscan H2 3d scanner provides high-quality raw scans that users can further refine or edit 3D scans using its inbuilt post-processing software."
    }
];

const FaqSection = () => {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const toggleFaq = (index: number) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <section className="bg-[#E6F3FF] py-12 md:py-20">
            <div className="container mx-auto px-4 md:px-8">
                <h2 className="mb-12 text-center text-3xl font-bold tracking-tight text-[#1D70B8] md:text-4xl">
                    FAQs
                </h2>
                <div className="mx-auto max-w-4xl space-y-4">
                    {faqs.map((faq, index) => (
                        <div key={index} className="overflow-hidden rounded-xl bg-white shadow-sm border border-blue-50">
                            <button
                                onClick={() => toggleFaq(index)}
                                className="flex w-full items-center justify-between px-6 py-5 text-left transition-colors hover:bg-gray-50"
                            >
                                <span className="text-lg font-bold text-gray-800">{faq.question}</span>
                                {openIndex === index ? (
                                    <ChevronUp className="size-5 text-[#1D70B8]" />
                                ) : (
                                    <ChevronDown className="size-5 text-gray-400" />
                                )}
                            </button>
                            <div
                                className={`overflow-hidden transition-all duration-300 ease-in-out ${openIndex === index ? 'max-h-[500px] border-t border-gray-100' : 'max-h-0'}`}
                            >
                                <div className="px-6 py-5 text-gray-600 leading-relaxed">
                                    {faq.answer}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default FaqSection;
